### ISSUE TITLE
Not working with latest Kodi Krypton build

### ISSUE THREAD

**Issue by Guilouz** [robwebset/script.tvtunes#1]
Hi,

Since these deprecated window names was removed from kodi, TVTunes not working (playing theme in background and theme downloading) : 

VideoLibrary
VideoFiles
Video
MusicLibrary
MusicFiles
Files
PVR
Scripts
InfoDialog
VisualisationSettings
NetworkSettings
TVSettings
GUICalibration

**Comment by robwebset** [comment]
http://forum.kodi.tv/showthread.php?tid=214287&pid=2369388#pid2369388
